print('********Y&S Tours and Travels***********')
print('Instructions:')
print('->Family/friends discount is applicable to 2 or 2+ members')
print('->Business discounts applicable only if company details and team travelling is provided')
print('-'*100)
print('International Destinations Available:')
print('1) Dubai')
print('2) Singapore')
print('3) New York')
print('4) Europe')
print('5) Russia')
print('6) Australia')
print('7) United Kingdom')
print('-'*100)
print("VARIOUS PACKAGES FOR EACH DESTINATION")
print("Dubai-Economical base package-1,20,000 Rs")
print("Singapore-Economical base package-1,00,000 Rs")
print("New York-Economical base package-1,90,000 Rs")
print("Europe-Economical base package-2,30,000 Rs")
print("Russia-Economical base package-1,60,000 Rs")
print("Australia-Economical base package-1,30,000 Rs")
print("United Kingdom-Economical base package-1,70,000 Rs")
print()
print('-'*70)
print("LUXURY PACKAGE AVAILABLE FOR THE ECONOMICAL PACKAGE FEE + 50,000 Rs")
print('-'*70)
print()
print("DISCOUNTS FOR FAMILY AND BUSINESS IS BASED ON NUMBER OF PEOPLE TRAVELLING*")
print("*More details given in the DISCOUNTS section")
print('-'*100)
print('DISCOUNTS GIVEN ON PACKAGE SELECTED:')
print('FAMILY DISCOUNTS: 8% discount for the package for each individual')
print('BUSINESS DISCOUNTS: 11% discount for the package for each individual')

