import sys
import time
def slowprint(s):
    s=s+'\n'
    for i in s:
        sys.stdout.write(i)
        sys.stdout.flush()
        time.sleep(0.01)
slowprint('𝕴𝖓𝖘𝖙𝖗𝖚𝖈𝖙𝖎𝖔𝖓𝖘')
print('->Family/Friends discount is applicable to 2 or 2+ members')
print('->Business discounts applicable only if company details and team travelling is provided')
print('-'*100)
slowprint('𝕯𝖊𝖘𝖙𝖎𝖓𝖆𝖙𝖎𝖔𝖓𝖘')
print('1) Dubai')
print('2) Singapore')
print('3) New York')
print('4) Europe')
print('5) Russia')
print('6) Australia')
print('7) United Kingdom')
slowprint('-'*100)
slowprint("𝕻𝖆𝖈k𝖆𝖌𝖊𝖘")
print("Below costs are base costs - costs will be increased by 15,000 Rs for each day of stay")
print("Dubai-Economical base package-50,000 Rs")
print("Singapore-Economical base package-75,000 Rs")
print("New York-Economical base package-100,000 Rs")
print("Europe-Economical base package-150,000 Rs")
print("Russia-Economical base package-130,000 Rs")
print("Australia-Economical base package-100,000 Rs")
print("United Kingdom-Economical base package-120,000 Rs")
slowprint('-'*70)
print("LUXURY PACKAGE AVAILABLE FOR THE ECONOMICAL PACKAGE FEE + 50,000 Rs")
slowprint('-'*70)
slowprint('𝕯𝖎𝖘𝖈𝖔𝖚𝖓𝖙𝖘:')
print('FAMILY DISCOUNTS: 8% discount for the package for each individual')
print('BUSINESS DISCOUNTS: 11% discount for the package for each individual')
slowprint('-'*70)
